apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome  
  labels:
    app: welcome
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      containers:
      - name: welcome
        image: mgaikwad49/welcome:latest 
        ports:
        - containerPort: 8080
